public enum EventID
{
    BALL_SELECTING,
    BALL_CONNECTING,
    BALL_RELEASING,
    BALL_EXPLOSION,
    BALL_EXPLODED,
    CLEARING_SELECTED_BALL,
    BOARD_SHIFTING_DOWN,
    BOOSTER_INVENTORY_CHANGE,
    BOOSTER_SELECTING,
    BOOSTER_SELECTED,
    BOOSTER_DESELECTING,
    BOOSTER_USING
}
